# maps defect type to severity level
defect_severity = {
    'Adhesive Cracks': 'LOW',
    'Adhesive Voids': 'HIGH',
    'CoreGap': 'LOW',
    'Cuts in Web Flange': 'HIGH',
    'Damaged Glass': 'HIGH',
    'Dust & dirt': 'NONE',
    'Entrained air': 'LOW',
    'Exposed core / Missing laminate': 'HIGH',
    'Foreign Objects': 'NONE',
    'Laminate Loose Edge': 'LOW',
    'Layer end': 'LOW',
    'Layer misplacement': 'HIGH',
    'Layers Overlap': 'HIGH',
    'LPS Cable Damage': 'HIGH',
    'Main SW Web Foot Lam': 'HIGH',
    'Metal Shavings': 'LOW',
    'RCO Bracket bond': 'SAFETY',
    'RCO Seal': 'NONE',
    'Repairs incorrect staggering': 'LOW',
    'Shearclips missing': 'NONE',
    'TE SW Web Foot Lam': 'HIGH',
    'TEBC Overlam Overlap': 'HIGH',
    'TEBC Paste Thickness': 'LOW',
    'TEBC Wave': 'HIGH',
    'Uncured laminate': 'LOW',
    'Other': 'NONE',
    'Voids Overlaminate': 'HIGH',
    'Waves Laminate': 'HIGH',
    "Core Offset": 'LOW',
    # added
    "Semi-Dry Glass / LFR": "LOW",
    "Delamination / LDL": "HIGH",
    "Core Misplacement / LCM": "LOW",
    "LPS Loose Cable": "LOW",
    "Laminate Roving Misplacement / LRM": "LOW",

    # "Excess Adhesive": "LOW",   <=== this one used to be one of the 3 before, but now it is not part of them anymore.
    "Foreign Objects / Adhered - Release film on surface": "NONE",
    "Foreign Objects / Adhered - Tacky tape on surface": "NONE",
    "Foreign Objects / Adhered - Green mesh, netting": "NONE",
    "Foreign Objects / Loose - Sandpaper Loose": "NONE",
    "Foreign Objects / Embedded - Object in bond line": "NONE",
    "Foreign Objects / Embedded - Vacuum Hose in bond line": "NONE",
    "Foreign Objects / Adhered - Masking tape on surface": "NONE",
    "Foreign Objects / Adhered - Resin Syringe, loose": "NONE",
    "Foreign Objects / Loose - Web separators (plastic tubes)": "NONE",
    "Foreign Objects / Adhered - Wood block, attached": "NONE",
    "Foreign Objects / Loose - Wood block, loose": "NONE",
    "Foreign Objects / Adhered - Web Catchers": "NONE",
}

# Colors used by opencv are in Blue,Green,Red format
defect_bgr_colors = {
    'Adhesive Cracks': (0, 234, 255),
    'Adhesive Voids': (0, 234, 255),
    'CoreGap': (0, 234, 255),
    'Cuts in Web Flange': (0, 234, 255),
    'Damaged Glass': (0, 234, 255),
    'Dust & dirt': (0, 234, 255),
    'Entrained air': (0, 234, 255),
    'Exposed core / Missing laminate': (0, 234, 255),
    'Foreign Objects':  (0, 234, 255),
    'Laminate Loose Edge': (0, 234, 255),
    'Layer end': (0, 234, 255),
    'Layer misplacement': (0, 234, 255),
    'Layers Overlap': (0, 234, 255),
    'LPS Cable Damage': (0, 234, 255),
    'Main SW Web Foot Lam': (0, 234, 255),
    'Metal Shavings': (0, 234, 255),
    'RCO Bracket bond': (0, 234, 255),
    'RCO Seal': (0, 234, 255),
    'Repairs incorrect staggering': (0, 234, 255),
    'Shearclips missing': (0, 234, 255),
    'TE SW Web Foot Lam': (0, 234, 255),
    'TEBC Overlam Overlap': (0, 234, 255),
    'TEBC Paste Thickness': (0, 234, 255),
    'TEBC Wave': (0, 234, 255),
    'Uncured laminate': (0, 234, 255),
    'Other': (0, 234, 255),
    'Voids Overlaminate': (0, 234, 255),
    'Waves Laminate': (0, 234, 255),
    "Core Offset":(0, 234, 255),
    # added
    "Semi-Dry Glass / LFR": (0, 234, 255),
    "Delamination / LDL": (0, 234, 255),
    "Core Misplacement / LCM": (0, 234, 255),
    "LPS Loose Cable": (0, 234, 255),
    "Laminate Roving Misplacement / LRM": (0, 234, 255),

    "Foreign Objects / Adhered - Release film on surface": (0, 234, 255),
    "Foreign Objects / Adhered - Tacky tape on surface": (0, 234, 255),
    "Foreign Objects / Adhered - Green mesh, netting": (0, 234, 255),
    "Foreign Objects / Loose - Sandpaper Loose": (0, 234, 255),
    "Foreign Objects / Embedded - Object in bond line": (0, 234, 255),
    "Foreign Objects / Embedded - Vacuum Hose in bond line": (0, 234, 255),
    "Foreign Objects / Adhered - Masking tape on surface": (0, 234, 255),
    "Foreign Objects / Adhered - Resin Syringe, loose": (0, 234, 255),
    "Foreign Objects / Loose - Web separators (plastic tubes)": (0, 234, 255),
    "Foreign Objects / Adhered - Wood block, attached": (0, 234, 255),
    "Foreign Objects / Loose - Wood block, loose": (0, 234, 255),
    "Foreign Objects / Adhered - Web Catchers": (0, 234, 255),

    # "Excess Adhesive": (0, 234, 255),
}

# assign colors to different defect categories
defect_severity_color = {'(?)': '#A52A2A', 'HIGH': '#FF4500',
                         'LOW': '#FFA500', 'SAFETY': '#9370D8', 'NONE': '#C0C0C0'}




